### ISSUE TITLE
For a map library try leaflet!

### ISSUE THREAD

**Issue by CodeDad70** [deadnancy/bus-tracker#2]
Checkout react-leaflet.org
Open source react map library, we use it at my work for interactive map components and laying graphics over maps!
Also it pays nice with Material for easy icons, and layout stuff

**Comment by mfletchernyc** [comment]
Hi @CodeDad70. I _am_ using react-leaflet! `src/Tracker.js` lines 4-6:

```
import {
  CircleMarker, GeoJSON, MapContainer, Marker, TileLayer
} from 'react-leaflet'
```
